### ISSUE TITLE
Časy nízkého tarifu pro kódy

### ISSUE THREAD

**Issue by Alloc186** [Antrac1t/HomeAssistant-EGDdistribuce#1]
Bylo by možné zadávat i konfiguraci ke kódům? (Příklad. můj kód je 197 198 199) Jak to mohu zadat? Povely s kombinací písmen a čísel platí pro Moravu a kódy pro Čechy.

A pokud ano, šel by senzor pak rozdělit zvlášť pro platnost NT, Vytápění a Ohřevu TV? (Mám Tarif D45d)

Díky moc, za pěkný Addon .)

**Comment by Antrac1t** [comment]
Omlouvám se za pozdní reakci, neočekával jsem, že si někdo bude addon instalovat :) ... Co se týče změny, potřeboval bych vědět vědět Váš HDO povel abych věděl jak parsovat json od egd distribuce.

**Comment by Alloc186** [comment]
To nevadí, i tak díky za odpověď. Zadávám ten kód pro jižní čechy, oblast České Budějovice, ten kód je jako jsem psal výše, kombinace tří trojčíslí: 197 198 199. V aplikace na android Distribuce mi to funguje fajn, ale chtěl jsem mít info i pro Home Assistant.

![HDO](https://user-images.githubusercontent.com/37019014/161346175-9f009e92-e5ae-40aa-ad3e-b258b758ea93.png)

**Comment by Antrac1t** [comment]
Díval jsem se na to a nemělo by být potřeba měnit kód, stačí pouze 3x udělat binary senzor. Doplňte pouze Vaše PSČ
`
binary_sensor:
  - platform: egddistribuce
    name: HDO - TAR
    psc: 
    code_a: "1"
    code_b: "7"
    code_dp: "01"

  - platform: egddistribuce
    name: HDO - PV
    psc: 
    code_a: "1"
    code_b: "7"
    code_dp: "02"

  - platform: egddistribuce
    name: HDO - TUV
    psc: 
    code_a: "1"
    code_b: "7"
    code_dp: "03"
`

**Comment by Alloc186** [comment]
Tak hlasím že mi to takto opravdu funguje, paráda! Jen jsem nějak pořád nepochopil tu šifru rozkladu kódu na (A,B,DP).

Každopádně Vám moc díky za pomoc, nyní senzory mohu dál využít v automatizacích :) což byl můj cíl.

**Comment by Antrac1t** [comment]
Manuálně jsem prošel json s raw datama a našel jsem pattern pro Váš kód, ale musím popřemýšlet jak převádět tříciferný kód na A,B,DP. Každopádně jsem rád, že addon využije aji někdo jiný než já :).

**Comment by Petrik-a-dost** [comment]
Zdravím @Antrac1t , já mám kód 405 406 410 a našel jsem převodní tabulku a výsledek by měl být:

binary_sensor:
  - platform: egddistribuce
    name: egdTAR
    psc: "38601"
    code_a: "3"
    code_b: "4"
    code_dp: "1"

  - platform: egddistribuce
    name: egdPV
    psc: "38601"
    code_a: "3"
    code_b: "4"
    code_dp: "2"

  - platform: egddistribuce
    name: egdTUV
    psc: "38601"
    code_a: "3"
    code_b: "4"
    code_dp: "6"

Ale asi to nefunguje nebo to mám špatně, můžete prosím zkontrolovat jestli je to správně? Předem díky

**Comment by Antrac1t** [comment]
Zdravím, code_dp musíte psát 01 02 06, posléze by mělo být vše v pořádku.

**Comment by Petrik-a-dost** [comment]
> Zdravím, code_dp musíte psát 01 02 06, posléze by mělo být vše v pořádku.

tyo supr, jede to. DÍKY moc. ještě se zeptám na označení:
egdTAR: Ovládání tarifu
egdPV: Přímotopové vytápění
egdTUV: Teplá užitková voda

Je to správně?

**Comment by Antrac1t** [comment]
> > Zdravím, code_dp musíte psát 01 02 06, posléze by mělo být vše v pořádku.
> 
> tyo supr, jede to. DÍKY moc. ještě se zeptám na označení: egdTAR: Ovládání tarifu egdPV: Přímotopové vytápění egdTUV: Teplá užitková voda
> 
> Je to správně?

ano, melo by to tak být
