### ISSUE TITLE
Sjednocení časů záznamů SPOTU a HDO

### ISSUE THREAD

**Issue by LubosKovar** [Antrac1t/HomeAssistant-EGDdistribuce#17]
Po updatu HDO senzor ukazuje grafy po 15min a SPOT cena je po 1h. Tím pádem při sloupcovém grafu linka SPOT ceny není skoro vidět. Navrhuji nějak sjednotit záznamy tak, aby byly jen v 1h intervalu. Nejsem si jist, zda někomu přepínají HDO jinak než v celou hodinu.

Druhý problém proti předchozí verzi je ten, že při najetí myší v grafu na nějaký čas se ukazuje cena dané hodiny jen pro HDO a ne i pro SPOT. Dříve se zobrazovaly obě ceny. HDO se skoro nemění ale SPOT cena každou hodinu. Takto nelze přesně zjisti, jaké bude cena pro vybranou hodinu. Toto se děje i v případě, že grafy nejsou sloupcové ale čárové.

![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/76791716/59ebb839-f0e8-4fd1-af32-a7834defe6d4)
![image (1)](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/76791716/03a0b740-02b6-47ec-a737-b39bb3a7b6ee)

**Comment by rattkin** [comment]
@Antrac1t prosím uzavřít
