### ISSUE TITLE
Nepřepíná

### ISSUE THREAD

**Issue by Kodlitko** [Antrac1t/HomeAssistant-EGDdistribuce#27]
V noci na dnešek došlo ke změně spínání HDO (region západ, pokyn 218 / A1B8DP06 pro D25d), ale integrace si nepřepla na nové časy.

Od půlnoci mám vše ve stavu _vypnuto_, ačkoliv NT měl běžet 2:30 - 6:00, teď od 14:00 - 15:30 a večer od 21:30 - 23:30.

V logu Home Assistant jsem našel varování:

```
Logger: py.warnings
Source: custom_components/egddistribuce/binary_sensor.py:117
Integration: egddistribuce ([documentation](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce), [issues](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/issues))
First occurred: 10:16:18 (2 occurrences)
Last logged: 10:16:19

/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'hdo.distribuce24.cz'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings warnings.warn(
```

Zkusil jsem do mého testovacího HA zanést opravu od @cewbdex (https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/pull/26), ale ani to nepomohlo - jen zmizela hláška z logu. Nějaké nápady?

**Comment by LubosKovar** [comment]
Hlásím stejnou chybu, byť u nás se časy neměnili. Od 0:00 dne 30.10. integrace vůbec nenačítá totiž hodnoty atributů.

![Snímek obrazovky 2023-10-30 145413](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/76791716/afc19dd7-579b-4baa-a999-4dd5e8fe5d61)

**Comment by IvoSvejcar** [comment]
Hlásím stejný problém, od dnešní půlnoci hlásí "vypnuto". Používám verzi 0.2.0, ale nefunguje to ani v té předchozí.

**Comment by LubosKovar** [comment]
Nejde to ani s verzí 0.2.0 ani s "main" Zkoušel jsem obě...moc prosíme autora o opravu....:-)

**Comment by Samot89** [comment]
Také stejná chyba od půlnoci nejde vypnuto

**Comment by Martin21186** [comment]
stejny problem :-)

**Comment by LubosKovar** [comment]
prosím @rattkin  o opravu kodu. Vypada to, že je nas vic zoufalych.....

**Comment by fistd** [comment]
mám stejný problém

**Comment by Kodlitko** [comment]
Dnes ráno jsem v logu našel ještě jednu chybovou hlášku:
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:885
First occurred: 04:54:52 (1 occurrences)
Last logged: 04:54:52

Updating state for binary_sensor.egdtar (<class 'custom_components.egddistribuce.binary_sensor.EgdDistribuce'>) took 10.403 seconds. Please create a bug report at https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/issues
```

**Comment by rattkin** [comment]
pošlete prosím konfiguraci z yaml, zkusím to.
Mě to pořád funguje, ale podívám se.

**Comment by Kodlitko** [comment]
konfigurace se kterou jsem do neděle fungoval:

```
binary_sensor:
    - platform: egddistribuce
      name: egdTAR
      psc: 39701
      code_a: "1"
      code_b: "8"
      code_dp: "06"
    - platform: egddistribuce
      name: egdTUV
      psc: 39701
      code_a: "1"
      code_b: "8"
      code_dp: "06"
```

Můj povel na přijímači HDO je 218, sazbu mám D25d. Kód A1B8DP06 jsem si pak dohledával ručně ve zdrojovém .json souboru z webu EGD. Verze souboru z půlky října má při porovnání s aktuálně staženým téměř poloviční velikost (479 kB vs 821 kB). Nemohlo dojít k nějaké změně formátu?

**Comment by Martin21186** [comment]
Moje nastavení 
![Screenshot_20231031_084427_Home Assistant](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/113773943/317a1897-b03e-4fa2-b3ae-3f195aa6bf1c)

**Comment by IvoSvejcar** [comment]
Já už asi půl roku jedu na tomhle, od 30. 10 od půlnoci už ne:

  - platform: egddistribuce
    name: HDO
    psc: 66401
    code_a: "1"
    code_b: "8"
    code_dp: "01"

Prosím o nápravu, díky moc.

Ivo

**Comment by HenryColdCZ** [comment]
Mám stejný problém. Restartoval jsem HomeAssistant, stáhl poslední verzi a nahrál ji, znovu restartoval. V logu je teď zmínka o neověřeném HTTPS požadavku

```
Logger: py.warnings
Source: custom_components/egddistribuce/binary_sensor.py:131
Integration: egddistribuce (documentation, issues)
First occurred: 09:39:43 (2 occurrences)
Last logged: 09:44:48

/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'hdo.distribuce24.cz'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings warnings.warn(
```

![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/145107207/db7c5470-ff73-4f83-aa4a-7d29688b6226)
![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/145107207/948e013d-704f-44a9-8565-f12fc16bd792)

**Comment by IvoSvejcar** [comment]
Ten požadavek na HTTPS tam mám v logu celou dobu provozování doplňku, ale nemělo to nikdy vliv na funkci …

**Comment by rattkin** [comment]
Proč máte 2x to samé?
Podle mne by vám stačila jen jedna entita, obě mají stejné nastavení.
Nevím zda to pomůže, ale zkuste.
A nemáte zadané ceny

děkuji, Jan Müller

Dne út 31. 10. 2023 8:41 uživatel Kodlitko ***@***.***>
napsal:

**Comment by rattkin** [comment]
Nemáte ceny

děkuji, Jan Müller

Dne út 31. 10. 2023 8:45 uživatel Martin21186 ***@***.***>
napsal:

**Comment by IvoSvejcar** [comment]
Ceny nepotřebuju a předpokládám, že nejsou povinnou položkou. Takže tady ta chyba doufám nebude. IS

**Comment by Martin21186** [comment]
![Screenshot_20231031_113233_Home Assistant](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/113773943/45da8d70-36b3-4c07-9968-d427120a6e4c)
Nakopiroval jsem kod podle návodu a ted configuration.yaml vyhazuje pořád chybu. Kde může být chyba?

**Comment by CooLajz** [comment]
Moje konfigurace od neděle pro D45d taky nefunguje :
- platform: egddistribuce
  name: HDO Nízký tarif
  psc: "66448"
  code_a: "1"  
  code_b: "8"
  code_dp: "01"
#  price_vt: "5.495"
#  price_nt: "5.080"

Aktuální verze v HA z HACS nevyžaduje ceny, konfigurace je nezná. 
Stáhl jsem aktuální verzi z GITu, zadal ceny, ale také mi to nejelo. V logu pouze chyba certifikátu, ale ta je tam stále.

Původně jsem si myslel, že mi to v neděli rozhodila sobotní změna času, protože i utility_meter byl o hodinu posunutý, nicméně po restartu HA v pondělí už byl v pořádku a resetoval se o půlnoci, ale tato integrace stále nefunguje :(

**Comment by Kodlitko** [comment]
@rattkin z historických důvodů, kdy jsem měl sazbu NT 16h (TAR), ale v něm bylo pouze 8h na ohřev bojleru (TUV). Mám na to navázané různé automatizace.

Cenu jsem zadanou neměl, a když ji zadám, HA hlásí neznámé nastavení price_vt a price_nt (jak zmiňuje @CooLajz).

**Comment by Kodlitko** [comment]
![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/42772673/b78d85ac-5376-4235-b7e8-ad8e7bfab5da)

**Comment by LubosKovar** [comment]
Pokud v HACS nactete plugin ve verzi 0.2.0, tak do YAML ceny VT a NT nedostanete, proto vam to haze chybu. Musite instalovat verzi "main", restart HA a pak do YAML pridat ty ceny. Kazdopadne plugin neco dela v obou verzich spatne, stale to nejede,...pls @rattkin moc o help....

**Comment by Kodlitko** [comment]
Teď jsem zkoušel na testovacím HA různé forky (@rattkin, @cewbdex), s jednou/dvěmi entitamy, s cenou/bez cen. A nefunguje ani jedna.

Možná došlo ke změně JSON souboru na straně EGD. Bohužel nejsem tak dobrý programátor, abych to dokázal analyzovat.

Ale pro porovnání mám stažený soubor [hdoZaznamy.json](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/files/13216311/hdoZaznamy.json) z 18. října 2023. Tehdy jsem ho stahoval, abych zjistil kód AxByDPz pro povel 218. Tehdy integrace ještě fungovala.

**Comment by Kodlitko** [comment]
Vyzkoušel jsem si vystavit původní soubor na webu, modifikoval v něm platnost mého kódu HDO z 29.10.23 na 29.11.23 a nasměroval na něj downloader.py. Po restartu HA se časy zobrazily:

![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/42772673/bca7dd89-d78e-4f2e-a7d5-fb11be046bba)


![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/42772673/2825a01d-57e0-454e-9ba5-4de4cce84841)

Momentálně mám fork od @rattkin, který entity nezobrazí bez zadaných cen.

**Comment by LubosKovar** [comment]
No jestli nebude problém v dekodovani dat z webu EGD pravě "smart" elektroměr vs "klasické" HDO...protože od kamarádů vím, že jim to jede - mají smart. A my co tu "pláčeme" tak jedeme na klasku přes A-B-DP kody

**Comment by rattkin** [comment]
já mám taky smart.

najdete ty své kody v aktuálním souboru hdoZaznamy.json?

**Comment by LubosKovar** [comment]
> Teď jsem zkoušel na testovacím HA různé forky (@rattkin, @cewbdex), s jednou/dvěmi entitamy, s cenou/bez cen. A nefunguje ani jedna.
> 
> Možná došlo ke změně JSON souboru na straně EGD. Bohužel nejsem tak dobrý programátor, abych to dokázal analyzovat.
> 
> Ale pro porovnání mám stažený soubor [hdoZaznamy.json](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/files/13216311/hdoZaznamy.json) z 18. října 2023. Tehdy jsem ho stahoval, abych zjistil kód AxByDPz pro povel 218. Tehdy integrace ještě fungovala.

Jak jste ten soubor prosim stahnul? At muzeme aktualni poskytnout @rattkin

**Comment by LubosKovar** [comment]
jak jsem psal, problém je podle mě SMART vs KLASIKA...já mám tyto klasicke kody a to nejdede
![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/76791716/3f31dd26-c13c-45d9-8752-08eef5874683)

**Comment by Kodlitko** [comment]
@rattkin: povel, kód a moje časy v novém souboru jsou a dokonce tam jsou i ty staré s platností do 29. 10. 2023! V tom by mohl být ten problém...

Jinak odkazy na soubory EGD jsou v _downloader.py_ - [hdoAdresy.json](https://hdo.distribuce24.cz/region) a [hdoZaznamy.json](https://hdo.distribuce24.cz/casy).

Jak jsem psal již výše, aktuální hdoZaznamy.json je větší (821 kB) oproti tomu z [18.10.2023](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/files/13216311/hdoZaznamy.json) (479 kB), zřejmě protože obsahuje staré i nové časy.

Mnou upravený starý soubor jsem si vystavil zde: https://home.korenius.net/~kodl/hdoZaznamy.json
Hromadně jsem v něm upravil platnost z `"do":{"den":"29","mesic":"10","rok":"2023"` na `"do":{"den":"29","mesic":"11","rok":"2023"` a v testovacím HA to funguje:
![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/42772673/c4a06ffd-9a6b-4771-be0b-1fc49bfbb4d7)

**Comment by Kodlitko** [comment]
Ještě mne napadlo, jestli integrace nemá problém v tom, že nový rozvrh spíná NT 3x denně. Za blahé paměti je to asi poprvé, co mám tři časy.

Starý povel:
```
[
   {
      "region":"ZAPAD",
      "skupinaPovelu":"218",
      "kodHdo_A":"218",
      "kodHdo_B":"A1B8DP6",
      "kodHdo_C":"1B8DP6",
      "kodHdo_D":"1B8P6",
      "kodHdo_E":"A1B8P6",
      "A":"1",
      "B":"8",
      "DP":"06",
      "sazby":[
         {
            "sazba":"D25d-relé1-TAR,TUV",
            "dny":[
               {
                  "denVTydnu":1,
                  "casy":[
                     {
                        "od":"02:30:00",
                        "do":"06:00:00"
                     },
                     {
                        "od":"14:30:00",
                        "do":"19:00:00"
                     }
                  ]
               },
               {
                  "denVTydnu":2,
                  "casy":[
                     {
                        "od":"02:30:00",
                        "do":"06:00:00"
                     },
                     {
                        "od":"14:30:00",
                        "do":"19:00:00"
                     }
                  ]
               },
               {
                  "denVTydnu":3,
                  "casy":[
                     {
                        "od":"02:30:00",
                        "do":"06:00:00"
                     },
                     {
                        "od":"14:30:00",
                        "do":"19:00:00"
                     }
                  ]
               },
               {
                  "denVTydnu":4,
                  "casy":[
                     {
                        "od":"02:30:00",
                        "do":"06:00:00"
                     },
                     {
                        "od":"14:30:00",
                        "do":"19:00:00"
                     }
                  ]
               },
               {
                  "denVTydnu":5,
                  "casy":[
                     {
                        "od":"02:30:00",
                        "do":"06:00:00"
                     },
                     {
                        "od":"14:30:00",
                        "do":"19:00:00"
                     }
                  ]
               },
               {
                  "denVTydnu":6,
                  "casy":[
                     {
                        "od":"03:00:00",
                        "do":"08:00:00"
                     },
                     {
                        "od":"15:00:00",
                        "do":"18:00:00"
                     }
                  ]
               },
               {
                  "denVTydnu":7,
                  "casy":[
                     {
                        "od":"03:00:00",
                        "do":"08:00:00"
                     },
                     {
                        "od":"15:00:00",
                        "do":"18:00:00"
                     }
                  ]
               }
            ]
         }
      ],
      "od":{
         "den":"02",
         "mesic":"09",
         "rok":"2023"
      },
      "do":{
         "den":"29",
         "mesic":"10",
         "rok":"2023"
      },
      "__v":0
   }
]
```

Nový povel
```
[
   {
      "region":"ZAPAD",
      "skupinaPovelu":"218",
      "kodHdo_A":"218",
      "kodHdo_B":"A1B8DP6",
      "kodHdo_C":"1B8DP6",
      "kodHdo_D":"1B8P6",
      "kodHdo_E":"A1B8P6",
      "A":"1",
      "B":"8",
      "DP":"06",
      "sazby":[
         {
            "sazba":"D25d-relé1-TAR,TUV",
            "dny":[
               {
                  "denVTydnu":1,
                  "casy":[
                     {
                        "od":"01:30:00",
                        "do":"06:00:00"
                     },
                     {
                        "od":"14:00:00",
                        "do":"15:30:00"
                     },
                     {
                        "od":"21:30:00",
                        "do":"23:30:00"
                     }
                  ]
               },
               {
                  "denVTydnu":2,
                  "casy":[
                     {
                        "od":"01:30:00",
                        "do":"06:00:00"
                     },
                     {
                        "od":"14:00:00",
                        "do":"15:30:00"
                     },
                     {
                        "od":"21:30:00",
                        "do":"23:30:00"
                     }
                  ]
               },
               {
                  "denVTydnu":3,
                  "casy":[
                     {
                        "od":"01:30:00",
                        "do":"06:00:00"
                     },
                     {
                        "od":"14:00:00",
                        "do":"15:30:00"
                     },
                     {
                        "od":"21:30:00",
                        "do":"23:30:00"
                     }
                  ]
               },
               {
                  "denVTydnu":4,
                  "casy":[
                     {
                        "od":"01:30:00",
                        "do":"06:00:00"
                     },
                     {
                        "od":"14:00:00",
                        "do":"15:30:00"
                     },
                     {
                        "od":"21:30:00",
                        "do":"23:30:00"
                     }
                  ]
               },
               {
                  "denVTydnu":5,
                  "casy":[
                     {
                        "od":"01:30:00",
                        "do":"06:00:00"
                     },
                     {
                        "od":"14:00:00",
                        "do":"15:30:00"
                     },
                     {
                        "od":"21:30:00",
                        "do":"23:30:00"
                     }
                  ]
               },
               {
                  "denVTydnu":6,
                  "casy":[
                     {
                        "od":"02:30:00",
                        "do":"07:00:00"
                     },
                     {
                        "od":"14:00:00",
                        "do":"16:00:00"
                     },
                     {
                        "od":"21:30:00",
                        "do":"23:00:00"
                     }
                  ]
               },
               {
                  "denVTydnu":7,
                  "casy":[
                     {
                        "od":"02:30:00",
                        "do":"07:00:00"
                     },
                     {
                        "od":"14:00:00",
                        "do":"16:00:00"
                     },
                     {
                        "od":"21:30:00",
                        "do":"23:00:00"
                     }
                  ]
               }
            ]
         }
      ],
      "od":{
         "den":"30",
         "mesic":"10",
         "rok":"2023"
      },
      "do":{
         "den":"31",
         "mesic":"01",
         "rok":"2024"
      },
      "__v":0
   }
]
```

**Comment by IvoSvejcar** [comment]
Tím to nebude, já mám stále 4 povely a nejedu taky. IS

**Comment by Busak007** [comment]
> > já mám taky smart.
> > najdete ty své kody v aktuálním souboru hdoZaznamy.json?
> 
> ![Screenshot_20231031_143528_Home Assistant](https://user-images.githubusercontent.com/113773943/279392541-c71b14cf-3c45-4df1-b76b-374aec562dc2.jpg) Mam jen toto v configuration.yaml a vypadá to ze to jede. Uvidim 16:15 jestli se vypne hdo


Pomohl by jste mi někdo prosím s nastavením mého configuration?

na elektroměru mám A1B4P3P12 D26
ceny VT a NT vím:
price_nt: "0,78"
price_vt: "1,29"

**Comment by rattkin** [comment]
desetinná čárka je podivný výmysl který mají jen v pár zemích. Zkuste
desetinnou tečku 0.78.

Děkuji.
S pozdravem Jan Müller

**Comment by IvoSvejcar** [comment]
OK, jestli to dobře chápu, byl odstraněn problém s chybou okolo HTTPS. Samotná chyba s nefunkčním doplňkem stále trvá?

**Comment by rattkin** [comment]
@IvoSvejcar našel jsem nějaké nesrovanlosti, dělám na tom

**Comment by rattkin** [comment]
zkuste můj fork, 
https://github.com/rattkin/HomeAssistant-EGDdistribuce
nebo můžete chvíli počkat než to @Antrac1t zamerguje, ale mělo by být všechno opravené.
Pokud vám to funguje, prosím zavřít problém.
Pokud ještě něco nejde, pošlete prosím konfig.

**Comment by HenryColdCZ** [comment]
Díky, funguje to

**Comment by CooLajz** [comment]
Super, uz je to mergnuté, otestováno a funguje.
Moc, moc díky!!!

**Comment by LubosKovar** [comment]
Potvrzuji. Funguje. Moc díky!

**Comment by Samot89** [comment]
Taky jede díky moc👍

**Comment by Kodlitko** [comment]
@Antrac1t udělal merge a po znovustažení přes HACS (verze main) již funguje. Ještě by to chtělo udělat tag nové verze pro HACS (https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/issues/11).

**Comment by Kodlitko** [comment]
Děkuji všem :-)

**Comment by CooLajz** [comment]
Bohužel se vrátil s touto verzí (ve verzi 0.2.0 to nebylo) takový nešvar, že pokud je nízký tarif přes půlnoc, tak se o té půlnoci na minutu vypne :(

**Comment by IvoSvejcar** [comment]
> Bohužel se vrátil s touto verzí (ve verzi 0.2.0 to nebylo) takový nešvar, že pokud je nízký tarif přes půlnoc, tak se o té půlnoci na minutu vypne :(

Jo, to je pravda. Nějak jsem to neřešil, protože mi to v podstatě nevadí, ale tohle tam předtím nebylo.

**Comment by rattkin** [comment]
Pošlete prosím config a data z atributu entity.
Asi tam bude chybět jedna řádka nebo tak něco

děkuji, Jan Müller

Dne st 1. 11. 2023 8:28 uživatel CooLajz ***@***.***> napsal:

**Comment by CooLajz** [comment]
- platform: egddistribuce
  name: HDO Nízký tarif
  psc: "66448"
  code_a: "1"  
  code_b: "8"
  code_dp: "01"
  price_vt: "5.495"
  price_nt: "5.080"

Dávám jen část přes půlnoc:
'2023-11-01T22:30:00+01:00': 5.08
'2023-11-01T22:45:00+01:00': 5.08
'2023-11-01T23:00:00+01:00': 5.08
'2023-11-01T23:15:00+01:00': 5.08
'2023-11-01T23:30:00+01:00': 5.08
'2023-11-01T23:45:00+01:00': 5.08
'2023-11-02T00:00:00+01:00': 5.08
'2023-11-02T00:15:00+01:00': 5.08
'2023-11-02T00:30:00+01:00': 5.08
'2023-11-02T00:45:00+01:00': 5.08
'2023-11-02T01:00:00+01:00': 5.08
'2023-11-02T01:15:00+01:00': 5.08
'2023-11-02T01:30:00+01:00': 5.08
'2023-11-02T01:45:00+01:00': 5.08
'2023-11-02T02:00:00+01:00': 5.08

problém bude ale s vypočítaným koncem 23:59:00, což je ta chybějící minuta do startu dalšího dne od 00:00:00
HDO Times: 00 - 08:15, 09:15 - 11:15, 12:15 - 14:45, 15:45 - 17:15, 18:15 - 23:59
HDO_Cas_Od: 00:00:00, 09:15:00, 12:15:00, 15:45:00, 18:15:00
HDO_Cas_Do: 08:15:00, 11:15:00, 14:45:00, 17:15:00, 23:59:00

**Comment by rattkin** [comment]
@CooLajz děkuji, ještě prosím vysvětlit kde je problém, co se vypne, entita?

v datech od EGd je od: 18:15, do: 23:59 a pak od: 00:00, do: 08:15 takže tam opravdu mezera je, mají blbě specifikaci souboru, pokud chtějí aby to šlo přes půlnoc plynule.
Ani nevím jak bych to měl v programu opravit.

**Comment by CooLajz** [comment]
Ano, entita jde na minutu off, takže pokud je něco nastaveno aby se vyplo ve vysokém tarifu tak se vypne na minutu. U některých spotřebičů jako je třeba tepelné čerpadlo to není úplně dobré.

**Comment by rattkin** [comment]
jedině mě napadá ke konci, pokud je poslední číslice 9, připočítat +1 minutu

**Comment by rattkin** [comment]
@CooLajz připravil jsem opravu, tak to prosím zkuste, zda to bude lepší
https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/pull/30

**Comment by CooLajz** [comment]
@rattkin otestoval jsem z Vašeho repozitáře a přes půlnoc to bylo v pořádku, nedošlo k minutovému přepnutí na vysoký.

**Comment by IvoSvejcar** [comment]
Ano, potvrzuji, o půlnoci NT bez přerušení. Díky moc.
