### ISSUE TITLE
Publikace do HACS default

### ISSUE THREAD

**Issue by Xeevis** [Antrac1t/HomeAssistant-EGDdistribuce#3]
Zdravím, 
v README je zobrazen HACS default badge

[![hacs_badge](https://img.shields.io/badge/HACS-Default-orange.svg?style=for-the-badge)](https://github.com/custom-components/hacs)

V defaultu tento repozitář ovšem není. Předpokládám, že to je artefakt z forkování [HomeAssistant-CEZdistribuce](https://github.com/zigul/HomeAssistant-CEZdistribuce). 

Správně tak má být

[![hacs_badge](https://img.shields.io/badge/HACS-Custom-41BDF5.svg?style=for-the-badge)](https://github.com/hacs/integration)

Mnohem lepší by ale bylo tento repozitář do defaultu publikovat. Je třeba tam splnit pár podmínek, vše je popsáno na odkazech v README na https://github.com/hacs/default ... Poté půjde EGD instalovat z HACS stejně jako PRE nebo CEZ distribuce bez nutnosti custom repozitáře.

![image](https://user-images.githubusercontent.com/5835044/190589465-42747a0d-f6d4-4be8-b6e6-2446c38f74a6.png)

**Comment by Antrac1t** [comment]
Zdravím, zkoušel jsem to, ale nedostanu se pres hassfest validaci (viz actions)

**Comment by Antrac1t** [comment]
Funguje, dík moc za help
