### ISSUE TITLE
Drobný problém s nízkým tarifem přes půlnoc

### ISSUE THREAD

**Issue by CooLajz** [Antrac1t/HomeAssistant-EGDdistribuce#4]
Zdravím,

pokud je nízký tarif přes půlnoc, je u EGD zobrazen čas nízkého tarifu např 21:45:00 - 23:59:00 a 00:00:00 - 08:30:00
Samozřejmě HDO na minutu nepřepne na vysoký... nešly by tyto půlnoční "akce" v rozšíření ošetřit?

![image](https://user-images.githubusercontent.com/20852771/190873055-dc64b56f-b6ed-452b-95f0-a33874290f80.png)

Díky

**Comment by Antrac1t** [comment]
snad opraveno, potreba zkontrolovat
