### ISSUE TITLE
Hlásím po aktualizaci  HA Operating System 9.5 je addon nefunkční

### ISSUE THREAD

**Issue by Samot89** [Antrac1t/HomeAssistant-EGDdistribuce#9]

**Comment by Alloc186** [comment]
Potvrzuji :/

**Comment by Antrac1t** [comment]
postnete error

**Comment by Samot89** [comment]
![image](https://user-images.githubusercontent.com/92251094/215854161-b146c74c-d965-4e3f-a7fb-fd745b34695e.jpeg)


Jedine co jsem nasel v logu

**Comment by Antrac1t** [comment]
potrebuji log z: nastaveni - system - logy

**Comment by Alloc186** [comment]
[home-assistant_2023-01-31T19-41-38.570Z.log](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/files/10550176/home-assistant_2023-01-31T19-41-38.570Z.log)

**Comment by Samot89** [comment]
Logger: homeassistant.loader
Source: loader.py:775 
First occurred: 19:17:36 (14 occurrences) 
Last logged: 19:17:36

We found a custom integration climate_group which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
We found a custom integration cz_energy_spot_prices which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
We found a custom integration circadian_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant


Primo chybu v logu na egd nemam ale toto je podobne te chybe co jsem posilal je to primo z logu jak jste psal jinak bohuzel nevim jak to udelat jinak?

**Comment by Antrac1t** [comment]
opraveno, aktualizujte pres HACS

**Comment by Alloc186** [comment]
Super, zdá se že už to funguje. Děkujeme za rychlou opravu!

**Comment by Samot89** [comment]
Super je funkcni dekuji za rychlou opravu;)
